import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { illustrationStatusPayload } from "@/lib/generation-status";
import { prisma } from "@/lib/prisma";
import {
  buildPreviewBookPages,
  previewIllustrationWhere,
} from "@/lib/preview-pages";

export async function GET(
  _request: Request,
  { params }: { params: { id: string } },
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "로그인이 필요합니다." }, { status: 401 });
  }

  const order = await prisma.storybookOrder.findFirst({
    where: { id: params.id, userId: session.user.id },
    select: { id: true },
  });

  if (!order) {
    return NextResponse.json({ error: "주문을 찾을 수 없습니다." }, { status: 404 });
  }

  const found = await prisma.illustration.findMany({
    where: { orderId: order.id, ...previewIllustrationWhere },
    select: {
      id: true,
      status: true,
      imagePath: true,
      pageType: true,
      pageNumber: true,
      isAutoGenerated: true,
    },
    orderBy: { pageNumber: "asc" },
  });
  const illustrations = buildPreviewBookPages(found)
    .filter((page) => page.id)
    .map((page) => ({
      id: page.id as string,
      status: page.status,
      imagePath: page.imagePath,
    }));

  return NextResponse.json(illustrationStatusPayload(illustrations));
}
