import type { IllustrationPageType, IllustrationStatus } from "@prisma/client";

export const previewIllustrationWhere = {
  OR: [
    { pageType: "COVER" as const },
    { pageType: "PAGE" as const, isAutoGenerated: true },
  ],
};

export type PreviewBookPage = {
  id: string | null;
  kind: "cover" | "page";
  pageNumber: number;
  label: string;
  status: IllustrationStatus;
  imagePath: string | null;
};

type IllustrationRow = {
  id: string;
  pageType: IllustrationPageType;
  pageNumber: number;
  isAutoGenerated: boolean;
  status: IllustrationStatus;
  imagePath: string | null;
};

function toBookPage(
  item: IllustrationRow | undefined,
  pageNumber: number,
): PreviewBookPage {
  const isCover = pageNumber === 1 || item?.pageType === "COVER";
  return {
    id: item?.id ?? null,
    kind: isCover ? "cover" : "page",
    pageNumber,
    label: isCover ? "표지" : String(pageNumber),
    status: item?.status ?? "IDLE",
    imagePath: item?.imagePath ?? null,
  };
}

export function buildFullBookPages(
  illustrations: IllustrationRow[],
  totalPages: number,
): PreviewBookPage[] {
  const byNumber = new Map(
    illustrations.map((item) => [item.pageNumber, item]),
  );

  return Array.from({ length: totalPages }, (_, index) => {
    const pageNumber = index + 1;
    return toBookPage(byNumber.get(pageNumber), pageNumber);
  });
}

export function buildPreviewBookPages(
  illustrations: IllustrationRow[],
): PreviewBookPage[] {
  const cover =
    illustrations
      .filter((item) => item.pageType === "COVER")
      .sort((a, b) => a.pageNumber - b.pageNumber)[0] ??
    illustrations.find((item) => item.pageNumber === 1);

  const autoPages = illustrations
    .filter((item) => item.pageType === "PAGE" && item.isAutoGenerated)
    .sort((a, b) => a.pageNumber - b.pageNumber)
    .slice(0, 2);

  const fallbackPages = illustrations
    .filter((item) => item.pageNumber === 2 || item.pageNumber === 3)
    .sort((a, b) => a.pageNumber - b.pageNumber)
    .slice(0, 2);

  const pages = autoPages.length > 0 ? autoPages : fallbackPages;

  return [
    {
      id: cover?.id ?? null,
      kind: "cover",
      pageNumber: cover?.pageNumber ?? 1,
      label: "표지",
      status: cover?.status ?? "IDLE",
      imagePath: cover?.imagePath ?? null,
    },
    {
      id: pages[0]?.id ?? null,
      kind: "page",
      pageNumber: pages[0]?.pageNumber ?? 2,
      label: String(pages[0]?.pageNumber ?? 2),
      status: pages[0]?.status ?? "IDLE",
      imagePath: pages[0]?.imagePath ?? null,
    },
    {
      id: pages[1]?.id ?? null,
      kind: "page",
      pageNumber: pages[1]?.pageNumber ?? 3,
      label: String(pages[1]?.pageNumber ?? 3),
      status: pages[1]?.status ?? "IDLE",
      imagePath: pages[1]?.imagePath ?? null,
    },
  ];
}
