import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import {
  buildPreviewBookPages,
  previewIllustrationWhere,
} from "@/lib/preview-pages";

function safeRevalidate(path: string) {
  try {
    revalidatePath(path);
  } catch {
    // CLI / non-Next context (tsx scripts) has no app router cache.
  }
}

export function revalidateOrderPreview(orderId: string) {
  safeRevalidate(`/dashboard/orders/${orderId}/preview`);
  safeRevalidate(`/dashboard/orders/${orderId}`);
  safeRevalidate("/dashboard");
  safeRevalidate(`/admin/illustrations/${orderId}`);
  safeRevalidate("/admin/illustrations");
}

export async function markOrderPreviewGeneratedIfReady(orderId: string) {
  const pages = await prisma.illustration.findMany({
    where: { orderId, ...previewIllustrationWhere },
    select: {
      id: true,
      status: true,
      pageType: true,
      pageNumber: true,
      isAutoGenerated: true,
      imagePath: true,
    },
  });
  const preview = buildPreviewBookPages(pages);

  if (
    preview.some(
      (page) => !page.id || page.status !== "COMPLETED" || !page.imagePath,
    )
  ) {
    revalidateOrderPreview(orderId);
    return;
  }

  try {
    await prisma.storybookOrder.updateMany({
      where: { id: orderId, previewGeneratedAt: null },
      data: { previewGeneratedAt: new Date() },
    });
  } catch (error) {
    console.error("previewGeneratedAt update failed", error);
  }
  revalidateOrderPreview(orderId);
}
