import type { IllustrationPageType, IllustrationStatus } from "@prisma/client";

/** 결제 전 미리보기: 표지 + 본문 1페이지(기상) + 본문 3페이지(동물). */
export const PREVIEW_PAGE_NUMBERS = [1, 2, 4] as const;

export const previewIllustrationWhere = {
  OR: [
    { pageType: "COVER" as const },
    { pageType: "PAGE" as const, isAutoGenerated: true },
  ],
};

export type PreviewBookPage = {
  id: string | null;
  kind: "cover" | "page";
  pageNumber: number;
  label: string;
  status: IllustrationStatus;
  imagePath: string | null;
};

type IllustrationRow = {
  id: string;
  pageType: IllustrationPageType;
  pageNumber: number;
  isAutoGenerated: boolean;
  status: IllustrationStatus;
  imagePath: string | null;
};

function toBookPage(
  item: IllustrationRow | undefined,
  pageNumber: number,
): PreviewBookPage {
  const isCover = pageNumber === 1 || item?.pageType === "COVER";
  return {
    id: item?.id ?? null,
    kind: isCover ? "cover" : "page",
    pageNumber,
    label: isCover ? "표지" : String(pageNumber - 1),
    status: item?.status ?? "IDLE",
    imagePath: item?.imagePath ?? null,
  };
}

export function buildFullBookPages(
  illustrations: IllustrationRow[],
  totalPages: number,
): PreviewBookPage[] {
  const byNumber = new Map(
    illustrations.map((item) => [item.pageNumber, item]),
  );

  return Array.from({ length: totalPages }, (_, index) => {
    const pageNumber = index + 1;
    return toBookPage(byNumber.get(pageNumber), pageNumber);
  });
}

export function buildPreviewBookPages(
  illustrations: IllustrationRow[],
): PreviewBookPage[] {
  const byNumber = new Map(
    illustrations.map((item) => [item.pageNumber, item]),
  );

  return PREVIEW_PAGE_NUMBERS.map((pageNumber) => {
    return toBookPage(byNumber.get(pageNumber), pageNumber);
  });
}
