import { revalidatePath } from "next/cache";
import { runIllustrationGeneration } from "@/lib/illustration-generate";
import { parseIdList, parseStringRecord } from "@/lib/orders";
import { prisma } from "@/lib/prisma";
import {
  buildPreviewBookPages,
  previewIllustrationWhere,
} from "@/lib/preview-pages";

function previewPrompts(
  title: string,
  characterLabels: string[],
  customValues: Record<string, string>,
) {
  const names = characterLabels.join(", ") || "주인공";
  const extras = Object.values(customValues)
    .map((value) => value.trim())
    .filter(Boolean)
    .join(", ");
  const extraText = extras ? ` ${extras}.` : "";

  return [
    {
      pageNumber: 1,
      prompt: `그림책 표지. 제목: ${title}. 주인공: ${names}.${extraText} 밝고 사랑스러운 그림책 표지.`,
    },
    {
      pageNumber: 2,
      prompt: `그림책 장면 1. ${title}. 주인공: ${names}이(가) 이야기의 시작을 맞이합니다.${extraText}`,
    },
    {
      pageNumber: 3,
      prompt: `그림책 장면 2. ${title}. 주인공: ${names}이(가) 즐거운 순간을 보냅니다.${extraText}`,
    },
  ];
}

export function revalidateOrderPreview(orderId: string) {
  revalidatePath(`/dashboard/orders/${orderId}/preview`);
  revalidatePath(`/dashboard/orders/${orderId}`);
  revalidatePath("/dashboard");
}

export async function markOrderPreviewGeneratedIfReady(orderId: string) {
  const pages = await prisma.illustration.findMany({
    where: { orderId, ...previewIllustrationWhere },
    select: {
      id: true,
      status: true,
      pageType: true,
      pageNumber: true,
      isAutoGenerated: true,
      imagePath: true,
    },
  });
  const preview = buildPreviewBookPages(pages);

  if (
    preview.some(
      (page) => !page.id || page.status !== "COMPLETED" || !page.imagePath,
    )
  ) {
    revalidateOrderPreview(orderId);
    return;
  }

  try {
    await prisma.storybookOrder.updateMany({
      where: { id: orderId, previewGeneratedAt: null },
      data: { previewGeneratedAt: new Date() },
    });
  } catch (error) {
    console.error("previewGeneratedAt update failed", error);
  }
  revalidateOrderPreview(orderId);
}

export async function startOrderPreviewGeneration(orderId: string) {
  const order = await prisma.storybookOrder.findUnique({
    where: { id: orderId },
    include: {
      template: { select: { title: true } },
      illustrations: {
        select: {
          id: true,
          pageNumber: true,
          status: true,
          pageType: true,
          isAutoGenerated: true,
        },
      },
    },
  });

  if (!order) {
    return;
  }

  const characterIds = parseIdList(order.selectedCharacterIds);
  const characters = await prisma.character.findMany({
    where: { id: { in: characterIds } },
    select: { id: true, label: true },
  });
  const labels = characterIds
    .map((id) => characters.find((character) => character.id === id)?.label)
    .filter((label): label is string => Boolean(label));
  const customValues = parseStringRecord(order.customInputValues);
  const prompts = previewPrompts(order.template.title, labels, customValues);

  if (order.illustrations.length === 0) {
    await prisma.illustration.createMany({
      data: prompts.map((page) => ({
        orderId,
        pageNumber: page.pageNumber,
        prompt: page.prompt,
        selectedCharacterIds: characterIds,
        pageType: page.pageNumber === 1 ? "COVER" : "PAGE",
        isAutoGenerated: true,
      })),
    });
  }

  const pages = await prisma.illustration.findMany({
    where: { orderId, ...previewIllustrationWhere },
    orderBy: { pageNumber: "asc" },
  });

  for (const page of pages) {
    if (page.status === "COMPLETED" || page.status === "PROCESSING") {
      continue;
    }

    const planned = prompts.find((item) => item.pageNumber === page.pageNumber);
    await runIllustrationGeneration({
      illustrationId: page.id,
      prompt: page.prompt || planned?.prompt || order.template.title,
      characterIds,
    });
  }

  await markOrderPreviewGeneratedIfReady(orderId);
}
