import type { IllustrationPageType, IllustrationStatus } from "@prisma/client";

export const previewIllustrationWhere = {
  OR: [
    { pageType: "COVER" as const },
    { pageType: "PAGE" as const, isAutoGenerated: true },
  ],
};

export type PreviewBookPage = {
  id: string | null;
  kind: "cover" | "page";
  pageNumber: number;
  label: string;
  status: IllustrationStatus;
  imagePath: string | null;
};

export function buildPreviewBookPages(
  illustrations: Array<{
    id: string;
    pageType: IllustrationPageType;
    pageNumber: number;
    isAutoGenerated: boolean;
    status: IllustrationStatus;
    imagePath: string | null;
  }>,
): PreviewBookPage[] {
  const cover =
    illustrations
      .filter((item) => item.pageType === "COVER")
      .sort((a, b) => a.pageNumber - b.pageNumber)[0] ??
    illustrations.find((item) => item.pageNumber === 1);

  const autoPages = illustrations
    .filter((item) => item.pageType === "PAGE" && item.isAutoGenerated)
    .sort((a, b) => a.pageNumber - b.pageNumber)
    .slice(0, 2);

  const fallbackPages = illustrations
    .filter((item) => item.pageNumber === 2 || item.pageNumber === 3)
    .sort((a, b) => a.pageNumber - b.pageNumber)
    .slice(0, 2);

  const pages = autoPages.length > 0 ? autoPages : fallbackPages;

  return [
    {
      id: cover?.id ?? null,
      kind: "cover",
      pageNumber: cover?.pageNumber ?? 1,
      label: "표지",
      status: cover?.status ?? "IDLE",
      imagePath: cover?.imagePath ?? null,
    },
    {
      id: pages[0]?.id ?? null,
      kind: "page",
      pageNumber: pages[0]?.pageNumber ?? 2,
      label: String(pages[0]?.pageNumber ?? 2),
      status: pages[0]?.status ?? "IDLE",
      imagePath: pages[0]?.imagePath ?? null,
    },
    {
      id: pages[1]?.id ?? null,
      kind: "page",
      pageNumber: pages[1]?.pageNumber ?? 3,
      label: String(pages[1]?.pageNumber ?? 3),
      status: pages[1]?.status ?? "IDLE",
      imagePath: pages[1]?.imagePath ?? null,
    },
  ];
}
