-- CreateEnum
CREATE TYPE "IllustrationPageType" AS ENUM ('COVER', 'PAGE');

-- AlterTable
ALTER TABLE "Illustration" ADD COLUMN "pageType" "IllustrationPageType" NOT NULL DEFAULT 'PAGE';
ALTER TABLE "Illustration" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Backfill preview pages created before these columns existed.
UPDATE "Illustration"
SET "pageType" = 'COVER', "isAutoGenerated" = true
WHERE "pageNumber" = 1;

UPDATE "Illustration"
SET "pageType" = 'PAGE', "isAutoGenerated" = true
WHERE "pageNumber" IN (2, 3);
