import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { OrderPreviewBook } from "@/components/OrderPreviewBook";
import { prisma, withPrismaRetry } from "@/lib/prisma";
import { parseIdList } from "@/lib/orders";
import { storybookOrderOptionLines } from "@/lib/storybook-order-summary";
import {
  startOrderPaidGeneration,
  startOrderPreviewGeneration,
} from "@/lib/preview-generation";
import {
  buildFullBookPages,
  buildPreviewBookPages,
} from "@/lib/preview-pages";
import {
  FULL_BOOK_GENERATION_ENABLED,
  PREVIEW_PAGE_NUMBERS,
  shouldKickPendingIllustration,
  TOTAL_STORYBOOK_PAGES,
} from "@/lib/storybook-generation";

export default async function OrderPreviewPage({
  params,
}: {
  params: { id: string };
}) {
  const session = await auth();
  if (!session?.user?.id) {
    redirect(`/login?callbackUrl=/dashboard/orders/${params.id}/preview`);
  }

  const loadOrder = () =>
    prisma.storybookOrder.findFirst({
      where: {
        id: params.id,
        userId: session.user.id,
      },
      include: {
        template: true,
        artStyle: { select: { label: true } },
        illustrations: {
          orderBy: { pageNumber: "asc" },
        },
      },
    });

  let order = await withPrismaRetry(loadOrder);

  if (!order) {
    notFound();
  }

  const paid = order.paymentStatus === "PAID";
  const illustrations = order.illustrations;
  const previewPageSet = new Set<number>(PREVIEW_PAGE_NUMBERS);
  const showFullBook = paid && FULL_BOOK_GENERATION_ENABLED;
  const needsPaidPages =
    showFullBook &&
    (illustrations.length < TOTAL_STORYBOOK_PAGES ||
      illustrations.some(
        (page) =>
          !previewPageSet.has(page.pageNumber) &&
          shouldKickPendingIllustration(page),
      ));
  const needsPreviewPages =
    !paid &&
    PREVIEW_PAGE_NUMBERS.some((pageNumber) => {
      const page = illustrations.find((item) => item.pageNumber === pageNumber);
      return !page || shouldKickPendingIllustration(page);
    });

  let kicked = false;
  try {
    if (needsPaidPages) {
      await startOrderPaidGeneration(order.id);
      kicked = true;
    } else if (needsPreviewPages) {
      await startOrderPreviewGeneration(order.id);
      kicked = true;
    }
  } catch (error) {
    console.error("preview page generation kick failed", order.id, error);
  }

  if (kicked) {
    try {
      const refreshed = await withPrismaRetry(loadOrder);
      if (refreshed) {
        order = refreshed;
      }
    } catch (error) {
      console.error("preview page refresh failed", order.id, error);
    }
  }

  const previewIllustrations = order.illustrations.filter(
    (item) =>
      item.pageType === "COVER" ||
      (item.pageType === "PAGE" && item.isAutoGenerated),
  );
  const pages = showFullBook
    ? buildFullBookPages(order.illustrations, TOTAL_STORYBOOK_PAGES)
    : buildPreviewBookPages(
        previewIllustrations.length > 0
          ? previewIllustrations
          : order.illustrations,
      );

  const bookComplete = pages.every(
    (page) => page.id && page.status === "COMPLETED" && page.imagePath,
  );

  const characterIds = parseIdList(order.selectedCharacterIds);
  const characters = await withPrismaRetry(() =>
    prisma.character.findMany({
      where: { id: { in: characterIds } },
      select: { id: true, label: true },
    }),
  );
  const optionLines = storybookOrderOptionLines({
    selectedCharacterIds: order.selectedCharacterIds,
    customInputValues: order.customInputValues,
    heroAgeRange: order.heroAgeRange,
    supportingCast: order.supportingCast,
    artStyleLabel: order.artStyle?.label,
    includePhotoAlbum: order.includePhotoAlbum,
    quantity: order.quantity,
    templateTitle: order.template.title,
    templateCustomFields: order.template.customFields,
    templateCastRoles: order.template.castRoles,
    characterLabelsById: new Map(
      characters.map((character) => [character.id, character.label]),
    ),
  });

  return (
    <>
      <OrderPreviewBook
        title={order.template.title}
        backHref="/dashboard"
        pages={pages}
        paid={paid}
        ready={!paid && bookComplete}
        bookComplete={bookComplete}
        orderId={order.id}
        includePhotoAlbum={order.includePhotoAlbum}
        optionLines={optionLines}
        defaultEmail={session.user.email ?? undefined}
        defaultName={session.user.name ?? undefined}
      />
    </>
  );
}
