import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { IntervalRefresher } from "@/components/IntervalRefresher";
import { OrderPreviewBook } from "@/components/OrderPreviewBook";
import { illustrationStatusPayload } from "@/lib/generation-status";
import { prisma } from "@/lib/prisma";
import {
  startOrderPaidGeneration,
  startOrderPreviewGeneration,
} from "@/lib/preview-generation";
import {
  buildFullBookPages,
  buildPreviewBookPages,
} from "@/lib/preview-pages";
import {
  FULL_BOOK_GENERATION_ENABLED,
  PREVIEW_PAGE_NUMBERS,
  shouldKickPendingIllustration,
  TOTAL_STORYBOOK_PAGES,
} from "@/lib/storybook-generation";

export default async function OrderPreviewPage({
  params,
}: {
  params: { id: string };
}) {
  const session = await auth();
  if (!session?.user?.id) {
    redirect(`/login?callbackUrl=/dashboard/orders/${params.id}/preview`);
  }

  let order = await prisma.storybookOrder.findFirst({
    where: {
      id: params.id,
      userId: session.user.id,
    },
    include: {
      template: true,
      illustrations: {
        orderBy: { pageNumber: "asc" },
      },
    },
  });

  if (!order) {
    notFound();
  }

  const paid = order.paymentStatus === "PAID";
  const previewPageSet = new Set<number>(PREVIEW_PAGE_NUMBERS);
  const showFullBook = paid && FULL_BOOK_GENERATION_ENABLED;
  const needsPaidPages =
    showFullBook &&
    (order.illustrations.length < TOTAL_STORYBOOK_PAGES ||
      order.illustrations.some(
        (page) =>
          !previewPageSet.has(page.pageNumber) &&
          shouldKickPendingIllustration(page),
      ));
  const needsPreviewPages =
    !paid &&
    (order.illustrations.length === 0 ||
      order.illustrations.some(
        (page) =>
          previewPageSet.has(page.pageNumber) &&
          shouldKickPendingIllustration(page),
      ));

  if (needsPaidPages) {
    await startOrderPaidGeneration(order.id);
  } else if (needsPreviewPages) {
    await startOrderPreviewGeneration(order.id);
  }

  if (needsPaidPages || needsPreviewPages) {
    const refreshed = await prisma.storybookOrder.findFirst({
      where: { id: order.id, userId: session.user.id },
      include: {
        template: true,
        illustrations: {
          orderBy: { pageNumber: "asc" },
        },
      },
    });
    if (refreshed) {
      order = refreshed;
    }
  }

  const previewIllustrations = order.illustrations.filter(
    (item) =>
      item.pageType === "COVER" ||
      (item.pageType === "PAGE" && item.isAutoGenerated),
  );
  const pages = showFullBook
    ? buildFullBookPages(order.illustrations, TOTAL_STORYBOOK_PAGES)
    : buildPreviewBookPages(
        previewIllustrations.length > 0
          ? previewIllustrations
          : order.illustrations,
      );

  const waitingForGeneration = pages.some(
    (page) =>
      !page.id || page.status === "IDLE" || page.status === "PROCESSING",
  );
  const bookComplete = pages.every(
    (page) => page.id && page.status === "COMPLETED" && page.imagePath,
  );

  return (
    <>
      <IntervalRefresher
        active={waitingForGeneration}
        href={`/api/orders/${order.id}/status`}
        initialSignature={JSON.stringify(
          illustrationStatusPayload(
            (showFullBook ? order.illustrations : previewIllustrations)
              .filter((page) => page.id)
              .map((page) => ({
                id: page.id,
                status: page.status,
                imagePath: page.imagePath,
                pageNumber: page.pageNumber,
              })),
          ),
        )}
      />
      <OrderPreviewBook
        title={order.template.title}
        backHref="/dashboard"
        pages={pages}
        paid={paid}
        ready={!paid && bookComplete}
        bookComplete={bookComplete}
        orderId={order.id}
      />
    </>
  );
}
